In [1]:
import numpy as np

def qr_decomposition(A):
    n, m = A.shape
    Q = np.zeros((n, m))
    R = np.zeros((m, m))

    for j in range(m):
        v = A[:, j].copy()

        for i in range(j):
            R[i, j] = np.dot(Q[:, i], A[:, j])
            v -= R[i, j] * Q[:, i]

        R[j, j] = np.linalg.norm(v)
        if R[j, j] == 0:
            raise ValueError("Matrix has linearly dependent columns")
        Q[:, j] = v / R[j, j]

    return Q, R

In [2]:
A = np.array([[1.0, 1.0, 0.0],
              [1.0, 0.0, 1.0],
              [0.0, 1.0, 1.0]])

Q, R = qr_decomposition(A)
print("Matrix A:\n", A)
print("\nOrthogonal matrix Q:\n", Q)
print("\nUpper triangular matrix R:\n", R)
print("\nCheck A ≈ QR:\n", np.allclose(A, Q @ R))

Matrix A:
 [[1. 1. 0.]
 [1. 0. 1.]
 [0. 1. 1.]]

Orthogonal matrix Q:
 [[ 0.70710678  0.40824829 -0.57735027]
 [ 0.70710678 -0.40824829  0.57735027]
 [ 0.          0.81649658  0.57735027]]

Upper triangular matrix R:
 [[1.41421356 0.70710678 0.70710678]
 [0.         1.22474487 0.40824829]
 [0.         0.         1.15470054]]

Check A ≈ QR:
 True
