In [2]:
import numpy as np
data=np.array([[1,2],[2,3]])
print(data.shape)


(2, 2)


In [3]:
import torch

# Scalar (0D)
scalar = torch.tensor(5)

# Vector (1D)
vector = torch.tensor([1, 2, 3])

# Matrix (2D)
matrix = torch.tensor([[1, 2], [3, 4]])

# 3D Tensor
tensor3d = torch.tensor([[[1, 2], [3, 4]],
                         [[5, 6], [7, 8]]])

print(tensor3d)


tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


In [4]:
images = torch.rand(2, 3, 2, 2)  # [Batch, Channel, Height, Width]


In [5]:
x = torch.arange(9).view(3, 3)
flat = x.view(-1)  # Flattened
unsqueezed = flat.unsqueeze(0)  # Add a dimension
squeezed = unsqueezed.squeeze(0)  # Remove dimension

In [6]:
print(x)
print(flat)
print(unsqueezed)
print(squeezed)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])
tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8]])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])


In [8]:
# Creating a 2x3 tensor
my_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32)
print(my_tensor)
print(my_tensor.shape)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.Size([2, 3])


In [12]:
x1 = torch.rand(5, 5)
x2 = torch.rand(5, 1)

In [14]:
# Broadcasting x2 to match x1
result = x1 - x2
print(result)

tensor([[-0.5330, -0.4089, -0.2408, -0.0246, -0.5354],
        [ 0.2471, -0.4933, -0.1727, -0.2191,  0.0598],
        [ 0.1749,  0.4099,  0.0806, -0.4793,  0.1860],
        [-0.6243, -0.3374, -0.4008, -0.1701, -0.3649],
        [-0.0262, -0.2382, -0.1759, -0.0980,  0.0255]])
